apiVersion: v1
kind: Service
metadata:
  name: redis-chat-app
  namespace: redis-chat-app
spec:
  # NodePort чтобы можно было обратиться через web
  type: NodePort
  selector:
    app: redis-chat-app
  ports:
    - name: redis-chat-app
      port: 80
      targetPort: 8080
      nodePort: 30010
