apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chatApp.name }}
  namespace: {{ .Values.chatApp.namespace }}
  labels:
    app: {{ .Values.chatApp.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.chatApp.name }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.chatApp.containerPort }}
      nodePort: {{ .Values.chatApp.nodePort }}
