apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.redis.namespace }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  serviceName: {{ .Values.redis.serviceName }}
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: '{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}'
          ports:
            - containerPort: {{ .Values.redis.port }}
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: {{ .Values.redis.storage.size }}
        storageClassName: {{ .Values.redis.storage.className }}
